namespace XamlMinGW
{
    [bindable]
    [default_interface]
    runtimeclass MainWindowViewModel : Windows.UI.Xaml.Data.INotifyPropertyChanged, Windows.UI.Xaml.Data.ICustomPropertyProvider
    {
        String Message;
        String UserName;
        Windows.UI.Xaml.Input.ICommand GreetingCommand {get;};
    }
}